### ISSUE TITLE
Back end function is not working properly

### ISSUE THREAD

**Issue by weiren2** [lsst-camera-visualization/frontend-old#127]
Averagae_pixel waits for back end response and never gets the value for some reason. I will try to fix it after the final exams.

**Comment by weiren2** [comment]
Average_pixel works fine now. Seems to be a issue of server instead of code. 

However, show_boundary now is broken.

**Comment by jonthaler** [comment]
Thanks for working on this.  Don’t forget to study for exams ;)

Jon

**Comment by jonthaler** [comment]
average_pixel is working now, but response has been (for at least a few days) quite slow.  If slowness is a temporary (and unrelated) problem, you should close this issue.

Jon
