### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#155]
Add a versioning system, ie X.Y.Z, major, minor, fix

**Comment by jonthaler** [comment]
How does the user see the version?  Where is version info stored?

**Comment by jbpagliuco** [comment]
Top left

![image](https://cloud.githubusercontent.com/assets/8813879/21739832/a2522120-d46c-11e6-9dc3-d1d0e4871874.png)

**Comment by jbpagliuco** [comment]
The version is stored in a file on the server, and updated with each new commit
