### ISSUE TITLE
Defining rect or circ through the mouse

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#17]
Hold r for rect and c for circ, track the mouse for the specified coordinates. Format this correctly, and post it in the copy buffer. Another thing we can do is after typing rect or circ in the terminal, the mouse tracking will happen in the viewer and be posted to the terminal after mouse up.

**Comment by jbpagliuco** [comment]
The region should also be shown while defining it

**Comment by jbpagliuco** [comment]
https://clipboardjs.com/

**Comment by jbpagliuco** [comment]
The region can be selected through the firefly viewer. Use the keyword 'selected' in the terminal to reference the area. See the wiki page for example usage. Waiting to merged with the master.

**Comment by jonthaler** [comment]
Comparing your two examples:

> average_pixel box1 ffview (rect 1000 100 50 1000)
> average_pixel box1 ffview selected
> Suppose I use FF to define the rectangle (i.e., 1000 100 50 1000).  What is passed to the back end?  Is "selected" translated to "(rect 1000 100 50 1000)" so that the back end does not know how the region selection was done?

**Comment by jbpagliuco** [comment]
The terminal will translate any variable to whatever value was passed to the terminal. So yes, selected will be changed (rect 1000 100 50 1000) and then parsed by the terminal. So the command function will receive the same values as before. For instance, the average_pixel command function will get { 'box_id' : 'box1', 'viewer_id' : 'ffview', 'region' : [ rect, 1000, 100, 50, 1000 ] }. The backend does not know, nor does it care, about how it got region data. Once firefly implements circles, it will be the same thing, the backend gets the same data, regardless of how the user specified it. The file select_region.js shows the setting of the variable if you'd like to see it. 

----- Original Message -----
