### ISSUE TITLE
Bring up region command panel when selecting a region

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#176]
When the user presses Ctrl+Shift click (maybe change, i don't know how macs work), bring up the viewer command panel and execute the command on the selected amplifier

**Comment by jonthaler** [comment]
I think one can't use the Ctrl key.  How about either Opt-click, Opt-Shift-click, or just Shift-click?

**Comment by jbpagliuco** [comment]
We already use shift click for just selected, we can use opt click

**Comment by jonthaler** [comment]
Sorry, I was confused.  Yes, Opt-click should work.  I’ll change the documentation to reflect your choices.  

Jon

**Comment by jonthaler** [comment]
Note: MacOS traps the Ctrl key, and (I think) Linux traps Opt, so we need to avoid them.

**Comment by jonthaler** [comment]
This has been mostly resolved.  For remaining work, see #178.
