### ISSUE TITLE
Short term projects (Bugs and enhancements)

### ISSUE THREAD

**Issue by jonthaler** [lsst-camera-visualization/frontend-old#178]
**These projects have been itemized separately as issues 181-192, and 129.**

- Move Development to Production.
- Graphing:
Add a lin/log parameter to `graph` commands to control display format.  `lin` should be the default.
Add axis labels and histogram titles.
Add `graph_noise` and `graph_proj` commands
- Fix the `prescan`/`postscan` bug 
- Install the new "bottom of viewer window" layout.
- Define raft-scale hardware regions.
- Implement the `noise` analysis command.
- Implement image comparison functions: blink and image subtraction.
- Implement the `load_image` (by URI) command.
- Update the documentation to reflect the current implementation.
- Implement the display of solid region colors, when the FF documentation of color support is ready.

Longer-term issue:
- How to preserve pixel interesting features when zoomed out.  For example, how to display a single hot pixel when each display pixel is a 4x4 image pixel region.

**Comment by weiren2** [comment]
For the prescan/postscan bug, I think the way ds9 defines a box region is prone to off-by-one error. I'll try to use polygons instead to see if it works better.

**Comment by jonthaler** [comment]
OK.  However, it only seems to be off in the horizontal direction.  Is that consistent with your idea?

**Comment by jbpagliuco** [comment]
These should be made into separate issues so it's easier to track and work on everything
