### ISSUE TITLE
Implement the display of solid region colors.

### ISSUE THREAD

**Issue by jonthaler** [lsst-camera-visualization/frontend-old#192]
Implement the display of solid region colors, when the FF documentation of color support is ready.

**Comment by tgoldina** [comment]
Firefly _does not_ support region color changes, but you can specify color when adding a region. An example of region string with color definition can be found at [Region Support](https://github.com/Caltech-IPAC/firefly/blob/dev/docs/firefly-api-overview.md#region-support) section of API docs: 'image; box 250 250 100 80 0 # color=red'

Firefly supports color name or RGB hex value for the color as described in [DS9 docs](http://ds9.si.edu/doc/ref/region.html): 
```
The color property specifies the color of the region when rendered. DS9 recognizes many symbolic color names (i.e. "red", "green", "blue", "pink", etc) along with 3, 6, and 9 digit RGB hex values (#fff, #ffffff, #fffffffff)
Example: 
circle(100,100,20) # color=green
circle(100,100,20) # color=#48f
```

**Comment by jonthaler** [comment]
Thanks.  I think we can implement the desired functionality using this.

**Comment by jonthaler** [comment]
We can implement this by creating a new command, `colored_region viewer region color`, where `region` is any of the allowed region specifiers (especially named HW regions) and `color` is the color determined by the algorithm.  This command will not normally be invoked directly by the user, but will most often be used by the algorithm to create a colored image

An example of an algorithm (command) that would use it:  `noise_status viewer threshold1 threshold2`.  The algorithm will analyze each HW region in the CCD (or perhaps a larger or smaller part of the focal plane).  Each region will be colored like this: 
- noise < threshold1  -> green
- threshold1 < noise < threshold2 -> yellow
- threshold2 < noise  -> red

**Comment by jbpagliuco** [comment]
@tgoldina what we're looking for is a way to draw filled rectangles (or any kind of ds9 regions if possible), not just color the border

**Comment by tgoldina** [comment]
At the moment, Firefly does not support filled rectangles. DS9 region specifications do not include properties for fill or opacity. However it should not be too hard for us to extend DS9 region specifications by adding fillColor and fillOpacity to region properties. Still, this is extra work and needs to be approved. How critical this feature is for you and how soon do you need it?

**Comment by jonthaler** [comment]
This feature was requested by Aaron Roodman.  It has proved to be vary useful for Dark Energy Survey status displays during operation.  However, it is less important for the test stands, so is not high priority at this time.

**Comment by xiuqin** [comment]
Currently SUIT does not have plan to extend the ds9 region functionality in Firefly.  I could give you an estimate of work and discuss how to proceed when this function becomes critical.

**Comment by jonthaler** [comment]
Work on this issue should be deferred.
