### ISSUE TITLE
"Choose command ..." has become redundant.

### ISSUE THREAD

**Issue by jonthaler** [lsst-camera-visualization/frontend-old#199]
We now have the `Execute command over selected region` method.
Perhaps`Choose command ...` should be removed from the extended FF toolbar.
This would significantly simplify the interface, and reduce the interaction with FF functionality.

**Comment by jbpagliuco** [comment]
We need the choose command button on the toolbar to get the region information. As far as I know we can't get the drawn region without the user pressing the button.

**Comment by jonthaler** [comment]
OK.  It’s not worth asking for a change to the FF API now.  I’ll add a note to the documentation.

Jon

**Comment by jonthaler** [comment]
The parameters of a region drawn by the FF tool are not exposed to the user.  Consequently, we cannot  remove `Choose command ...` unless the FF API is changed.
