### ISSUE TITLE
Fix rect parameter ordering

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#35]
left top right bottom

**Comment by weiren2** [comment]
Use [lastest branch](https://github.com/lsst-camera-visualization/backend/tree/i/35_Params_Frontend) of backend to work with this parameter reordering issue.

Also, I'm not sure if it's a bug in the front end. But if the user types two points like `(rect 1000 1000 300 400)`, the rectangular region will parsed into `{x1:300, x2:300, y1:400, y2:400}`, which is a point basically. I'm expecting the region to be`{x1:300, x2:1000, y1:400, y2:1000}`. I'll have a look at the region parser.

**Comment by jonthaler** [comment]
I think it is more intuitive to the user if the parameter order is (rect x1,y1, x2,y2).
That is, (rect 1000 1000 300 400) should be parsed as x1=1000,y1=1000, x2=300,y2=400.
The back end will reorder it to be x1=300,y1=400, x2=1000,y2=1000, but the user shouldn't see this.  For clarity, the result box should display the parameters that the user entered.

**Comment by weiren2** [comment]
Okay I found the bug. When parsing the two coordinate, it changes the max and min in a in-place fashion. So `x1` will equal to `x2` if `x1>x2`. The same for `y1` and `y2`.

``` javascript
        rect.x1 = Math.min(rect.x1, rect.x2);
        rect.x2 = Math.max(rect.x1, rect.x2);
        rect.y1 = Math.min(rect.y1, rect.y2);
        rect.y2 = Math.max(rect.y1, rect.y2);
```

I removed the above part. Instead I directly use min and max of the input `x1 y1 x2 y2` when assigning values to `rect` region. Refer to this commit 9d5484d316407149ceaa9d20b1c26fee142903a5

``` javascript
        rect = {
            x1 : Math.min(Number(region[1]), Number(region[3])),
            y1 : Math.min(Number(region[2]), Number(region[4])),
            x2 : Math.max(Number(region[1]), Number(region[3])),
            y2 : Math.max(Number(region[2]), Number(region[4]))
        };
```

@jbpagliuco I also changed one line of code where it overlays the region user typed on top of the viewer. DS9 box regions are starting from top-left corner of the rectangle (though it seems weird to me). Previously the way the code written was defining the box staring from the bottom left.
