### ISSUE TITLE
Average pixel button

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#50]
When the user selects a region via firefly, there should be a button to automatically calculate the average pixel of that viewer, and send the results to some default box

**Comment by jonthaler** [comment]
More generally, as we build up a menu of functions (eg, hot_pixels, etc.) we will want "buttons" for each.  Perhaps the menu bar along the top of the terminal window can be made into menus (see image), allowing the user to select any option that is allowed at that moment.  Something similar could be done for the command, although the menu might become very long.  It might be feasible to shorten the list by only displaying choices that begin with already-typed text.

![terminal](https://cloud.githubusercontent.com/assets/14808549/17445149/18fba234-5b09-11e6-9811-59ebfeee74da.jpg)
