### ISSUE TITLE
List of possible boxes/viewers

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#56]
In the terminal, when hovering the box_id or viewer_id in the help string, show a list of boxes/viewers that are possible

**Comment by jbpagliuco** [comment]
@jonthaler Could you take a look at the branch i/56 and let me know if this works how you think it should?

**Comment by jonthaler** [comment]
Hi,

I have not been building the code on my computer - just running the main branch.  So, it will take me some time to come up to speed.

Jon
