### ISSUE TITLE
Terminal window does not display in Safari

### ISSUE THREAD

**Issue by jonthaler** [lsst-camera-visualization/frontend-old#58]
The ffview window does display.

**Comment by jbpagliuco** [comment]
@jonthaler  Do you get any errors in the console (F12 should bring it up)? I don't have a mac and Apple doesn't make Safari for other OS's anymore

**Comment by jonthaler** [comment]
console screenshot attached.

**Comment by jbpagliuco** [comment]
@jonthaler I don't see anything attached, could you resend it?

**Comment by jonthaler** [comment]
Bug went away.
