### ISSUE TITLE
Using a viewer id

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#6]
Most (if not all) commands use the viewer id 'ffview' as a hard coded value. It needs to use the viewer id that's passed in from the command line.

**Comment by babburra** [comment]
Can be fixed by adding var id = cmd_args[0]; and using id instead of 'ffview'.
I fixed some commands, other commands like FireflyOnLoaded need to be discussed I think.

**Comment by jbpagliuco** [comment]
Updated in master branch, except for load_image, which Stuart will have to do.
