### ISSUE TITLE
Collect information for updating install and configure docs

### ISSUE THREAD

**Issue by slm23** [lsst-camera-visualization/frontend-old#73]
Provide details of how firefly was configured to support frontend and backend codes...

**Comment by slm23** [comment]
My install notes are in the attached file.
[firefly-install.txt](https://github.com/lsst-camera-visualization/frontend/files/415843/firefly-install.txt)

**Comment by weiren2** [comment]
I've updated the documentation at https://github.com/lsst-camera-visualization/lsst_firefly.
