### ISSUE TITLE
Memory of settings

### ISSUE THREAD

**Issue by jbpagliuco** [lsst-camera-visualization/frontend-old#75]
What ever the user puts for his settings should be saved upon exiting and used upon opening

**Comment by jbpagliuco** [comment]
We could also keep track of all of the boxes and viewers that were created, as well as their positions, and restore them when the user comes back. If we do this, we should also have an easy way to restore everything to default

**Comment by jbpagliuco** [comment]
Not going to save boxes and viewers at this moment. Terminal settings are saved though.

**Comment by jonthaler** [comment]
How does the SW remember?  By a cookie, or by having user-IDs and sign-ins?

**Comment by jbpagliuco** [comment]
Every browser provides a thing called localStorage. So the user doesn't need to do anything, it's automatically saved via the browser.

**Comment by jonthaler** [comment]
Does localStorage persist if one quits the browser?  If not, this solution is less useful.

**Comment by jbpagliuco** [comment]
Yes it stays
