### ISSUE TITLE
Front end sends image urls to back end.

### ISSUE THREAD

**Issue by weiren2** [lsst-camera-visualization/frontend-old#89]
Whenever the front end invokes a back end function, it sends the command together with the url of the image.

**Comment by jonthaler** [comment]
The documentation should describe the structure of messages.  For example:
- What restrictions are imposed on the command name (disallowed characters?).
- Describe the syntax of the region descriptor.

**Comment by weiren2** [comment]
#100 
There are two additional functions in `viewer.js` that can return the uri of the image associated with the viewer. Currently they're just hard-coded as before. But once the image server is deployed we can configure it to find the link to the image.
- `getNewImageURL()` should get the FITS image of single extension.
- `getNewOriginalImageURL()` should get the multi-extension FITS image location in case user requests some tasks/analysis on the original image.
